version: "3.9"

services:
  # ---- Database ----
  db:
    image: postgres:15-alpine
    container_name: cm_db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB:       "${DB_NAME}"
      POSTGRES_USER:     "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - corn-moisture-network

  # ---- pgAdmin ----
  pgadmin:
    image: thajeztah/pgadmin4
    container_name: cm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: qi@qi.com
      PGADMIN_DEFAULT_PASSWORD: P@ssword
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - corn-moisture-network

  # ---- Auth Service ----
  auth-service:
    image: auth-service:latest
    container_name: cm_auth
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - corn-moisture-network

  # ---- Data Service ----
  data-service:
    image: data-service:latest
    container_name: cm_data
    restart: always
    ports:
      - "5002:5002"
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - corn-moisture-network

  # # ---- Interface Service ----
  # interface-service:
  #   image: interface-service:latest
  #   container_name: cm_interface
  #   restart: always
  #   ports:
  #     - "5103:5103"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:5103/health || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   networks:
  #     - corn-moisture-network

  # ---- Moisture Sensor ----
  moisture-sensor:
    image: moisture-sensor:latest
    container_name: cm_sensor
    restart: always
    ports:
      - "5004:5004"
    env_file:
      - ./.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5004/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    networks:
      - corn-moisture-network

  # ---- Frontend ----
  frontend:
    image: moisture-sensor-fe:latest
    container_name: cm_frontend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    networks:
      - corn-moisture-network
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin-data:

networks:
  corn-moisture-network: {}