# Stage 1: Build Stage
FROM python:3.9-bullseye AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev libopenblas-dev cmake gfortran \
    pkg-config python3-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt ./

# แยกไฟล์ requirements
RUN echo "\
numpy==1.22.4\n\
scipy==1.7.3\n\
scikit-learn==1.1.3\n\
pandas==2.2.3\n" > requirements-sci.txt

RUN echo "\
annotated-types==0.7.0\nanyio==4.6.2.post1\ncertifi==2024.8.30\ncharset-normalizer==3.4.0\nclick==8.1.7\ncolorama==0.4.6\nfastapi==0.115.4\nh11==0.14.0\nidna==3.10\npydantic==2.9.2\npydantic_core==2.23.4\npyModbusTCP==0.3.0\npython-dotenv==1.0.1\nrequests==2.32.3\nsniffio==1.3.1\nstarlette==0.41.2\ntyping_extensions==4.12.2\nurllib3==2.2.3\nuvicorn==0.32.0\npython-jose[cryptography]\nSQLAlchemy==2.0.41\npsycopg2-binary==2.9.10\nminimalmodbus==2.1.1\n" > requirements-base.txt

RUN python -m venv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install --prefer-binary -r requirements-base.txt && \
    /venv/bin/pip install --prefer-binary --only-binary=:all: \
    -r requirements-sci.txt \
    --extra-index-url https://www.piwheels.org/simple

# Stage 2: Final Image
FROM python:3.9-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 libopenblas0 && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1 PATH="/venv/bin:$PATH"

COPY --from=builder /venv /venv
COPY . /app
WORKDIR /app
